accounts/urls.py
from django.conf.urls import url

from . import views




urlpatterns = [
    url(r'^login/$', views.login_view,  name = "login"),
    url(r'^logout/$', views.logout_view, name = "logout"),
    url(r'^register/$', views.register_view, name = "register"),

]

blog/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static 
from django.contrib import admin
from posts import views

urlpatterns = [    
    url(r'^admin/', admin.site.urls),
    # url(r'^posts/$', "posts.views.post_home"),
    # url(r'^posts/$', "<app_name>.views.<function_name>"),
    url(r'^comments/', include("comments.urls", namespace = "comments")),
    url(r'^accounts/', include("accounts.urls", namespace = "accounts")),
    url(r'^', include("posts.urls", namespace = "posts")),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.conf.urls import url

from . import views




urlpatterns = [
    # url(r'^posts/$', "posts.views.post_home"),
    # url(r'^posts/$', "<app_name>.views.<function_name>"),
    url(r'^$', views.post_list, name = "list"),
    url(r'^create/$', views.post_create),
    url(r'^(?P<slug>[\w-]+)$', views.post_detail,  name = "detail"),
    # url(r'^list/$', views.post_list),
    url(r'^(?P<slug>[\w-]+)/edit$', views.post_update, name = "update"),
    url(r'^(?P<slug>[\w-]+)/delete/$', views.post_delete, name = "delete"),

]

accounts/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

posts/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.text import slugify

from markdown_deux import markdown

from comments.models import Comment
from .utils import get_read_time,count_words


# Create your models here.
# test 

class PostManager(models.Manager):
	def active(self, *args, **kwargs):
		return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
	return "%s/%s" %(instance.id, filename)


class Post(models.Model):
	author = models.ForeignKey(User, default=1)
	title = models.CharField(max_length = 200)
	slug = models.SlugField(unique=True)
	image = models.ImageField(upload_to=upload_location,
		null=True, blank=True, 
		height_field="height_field", 
		width_field="width_field")
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	content = models.TextField()
	draft = models.BooleanField(default= False)
	publish = models.DateField(auto_now = False, auto_now_add = False, )
	words_count = models.IntegerField(default=0)
	read_time = models.IntegerField(default=0)
	updated = models.DateTimeField(auto_now = True, auto_now_add = False)
	timestamp = models.DateTimeField(auto_now = False, auto_now_add = True)
	test = models.BooleanField(default= False)

	objects = PostManager()


	def __unicode__(self):
		return self.title

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("posts:detail", kwargs={"slug": self.slug})
		# return "post/%s/" %(self.id)  # hard coded urls

	class Meta:
		ordering = ["-timestamp", "-updated"]

	def get_markdown(self):
		content = self.content
		markdown_text = markdown(content)
		return mark_safe(markdown_text)

	@property
	def comments(self):
		instance = self
		qs = Comment.objects.filter_by_instance(instance)
		return qs
	

	@property
	def get_content_type(self):
		instance = self
		content_type = ContentType.objects.get_for_model(instance.__class__)
		return content_type
	



def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.content:
    	html_string = instance.get_markdown()
    	instance.words_count = count_words(html_string)
    	instance.read_time = get_read_time(html_string)



pre_save.connect(pre_save_post_receiver, sender=Post)

accounts/forms.py
from django import forms

from django.contrib.auth import authenticate, get_user_model, login, logout


User = get_user_model()

class UserLoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)

	def clean(self, *args, **kwargs):
		username = self.cleaned_data.get("username")
		password = self.cleaned_data.get("password")
		if username and password:
			user_qs = User.objects.filter(username=username)
			if user_qs.count() == 0:
				raise forms.ValidationError("The user does not exist")
			else:
				user = authenticate(username=username, password=password)
				if not user:
					raise forms.ValidationError("Incorrect password")
				if not user.is_active:
					raise forms.ValidationError("This user is no longer active")
		return super(UserLoginForm, self).clean(*args, **kwargs)



class UserRegisterForm(forms.ModelForm):
	email = forms.EmailField(label='Email address')
	email_2 = forms.EmailField(label='Confirm Email')
	password = forms.CharField(widget=forms.PasswordInput)
	class Meta:
		model = User
		fields = [
			'username',
			'email',
			'email_2',
			'password',
		]


	def clean_email_2(self):
		email = self.cleaned_data.get('email')
		email_2 = self.cleaned_data.get('email_2')
		if not email == email_2:
			raise forms.ValidationError("Emails must match")

		email_qs = User.objects.filter(email=email)
		if email_qs.exists():
			raise forms.ValidationError("This email has already been registered")
		return email

posts/forms.py
from django import forms

from pagedown.widgets import PagedownWidget

from .models import Post



class PostForm(forms.ModelForm):
	content = forms.CharField(widget=PagedownWidget(show_preview=False))

	publish = forms.DateField(widget=forms.SelectDateWidget)
	class Meta:
		model = Post
		fields = [
			"title",
			"content",
			"image",
			"draft",
			"publish",
		]

accounts/views.py
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

from .forms import UserLoginForm, UserRegisterForm

# Create your views here.


def login_view(request):
	title = "Login"
	next = request.GET.get('next')
	form = UserLoginForm(request.POST or None)
	if form.is_valid():
		username = form.cleaned_data.get("username")
		password = form.cleaned_data.get("password")
		user = authenticate(username=username, password=password)
		login(request, user)
		if next:
			return redirect(next)
		return redirect("posts:list")
		
	context = {
		"title": title,
		"form": form,
	}
	return render(request, "accounts.html", context)


def logout_view(request):
	logout(request)
	return redirect("posts:list")





def register_view(request):
	title = "Register"
	next = request.GET.get('next')
	form = UserRegisterForm(request.POST or None)
	if form.is_valid():
		user = form.save(commit=False)
		password = form.cleaned_data.get('password')
		user.set_password(password)
		user.save()

		new_user = authenticate(username=user.username, password=password)
		login(request, new_user)
		if next:
			return redirect(next)
		return redirect("posts:list")

	context = {
		"title": title,
		"form": form,
	}
	return render(request, "accounts.html", context)

templates/accounts.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}


<div class="col-sm-6 col-sm-offset-3">

<h1>{{ title }}</h1><hr />

<form method="POST" action="" enctype="multipart/form-data">
{% csrf_token %}
{{ form|crispy }}
<input type="submit", value="{{ title }}" class="btn btn-primary" role="button">
</form>
</div>

{% endblock content %}

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="Rayiyaoyao">
 


    <!-- Bootstrap core CSS -->
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="http://getbootstrap.com/assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

  	<!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
  



    <link rel="icon" href="{% static 'images/favicon.ico' %}">


    <title>{% block title %}{{ title }}{% endblock title %}</title>

    {% block head_extra %}{% endblock %}

</head>

<body>



{% include "messages_display.html" %}
<div class="strip" style="background:#db4c3f; top:0; left:0; height:4px; width:100%;"></div>

<a href="{% url 'posts:list' %}" class="logo"></a>



{% block content %}

{% endblock content %}




<!-- Latest compiled and minified JavaScript -->


<script src="{% static 'js/jquery.js' %}"></script>
  <script src="{% static 'js/modernizr.js' %}"></script>  
  <script src="{% static 'js/main.js' %}"></script>

<script type="text/javascript">
$(document).ready(function(){
	$(".content-markdown").each(function(){
		var content = $(this).text()
		var markedContent = marked(content)
		$(this).html(markedContent)
		})


	// preview_title
	var titleInput = $("#id_title");
	// $("#preview-title").html(titleItem.val())
	function setTitle(value){
		$("#preview-title").text(value)
	}
	setTitle(titleInput.val())
	titleInput.keyup(function(){
		var newTitle = $(this).val()
		setTitle(newTitle)
	})


	// preview_content
	var contentInput = $("#id_content");
	// $("#preview-content").html(marked(contentItem.val()))
	function setContent(value){
		var markedContent = marked(value)
		$("#preview-content").html(markedContent)
		$("#preview-content img").each(function(){
			$(this).addClass("img-responsive")
		})
	}
	setContent(contentInput.val())

	contentInput.keyup(function(){
		// console.log($(this).val());
		var newContent = $(this).val()
		setContent(newContent)
	})

	$(".comment-reply-btn").click(function(event){
		event.preventDefault();
		$(this).parent().next(".comment-reply").fadeToggle();
	})

})



</body>


</html>

templates/comment_delete.html
{% extends "base.html" %}


{% load urlify %}
{% load crispy_forms_tags %}


{% block content %}
<div class="col-sm-6 col-sm-offset-3 ">

<div class="comment">
<h1>Confirm Delete</h1>
	
		<form method="POST", action="">
		{% csrf_token %}
		<p>Are you sure you want to delete: "{{ object.content }}"?</p>
		
		<input type="submit" value="Confirm" class="btn btn-warning" />
		<a href="{{ object.get_absolute_url }}" class="btn btn-default">Cancel</a>
		</form>
	</div>


</div>


{% endblock content %}

templates/comment_thread.html
{% extends "base.html" %}


{% load urlify %}
{% load crispy_forms_tags %}


{% block content %}
<div class="col-sm-6 col-sm-offset-3 ">

<div class="comment">
	<p class="lead">Comments</p>
	

	<p>{{ comment.content }}</p>
	<footer>{{ comment.user }} | {{ comment.timestamp|timesince }} ago
	{% if comment.children.count > 0 %} | {{ comment.children.count }} replies{% endif %}{% if request.user == comment.user %} | <a href="{{ comment.get_delete_url }}" >Delete</a>{% endif %}
	<!-- <a class="comment-reply-btn" href="#">Reply</a> -->
	</footer>
	<hr />
	<div  >
		{% for child_comment in comment.children %}
		<blockquote>
		<p>{{ child_comment.content }}</p>
		<footer>{{ child_comment.user }} | {{ child_comment.timestamp|timesince }} ago{% if request.user == child_comment.user %} | <a href="{{ child_comment.get_delete_url }}" >Delete</a>{% endif %}</footer>
		</blockquote>
		{% endfor %}
		
		{% if request.user.is_authenticated %}
		<form method="POST", action="">
		{% csrf_token %}
		{{ comment_form|crispy }}
		<input type="hidden" name="parent_id" value="{{ comment.id }}" />
		<input type="submit" value="Reply" class="btn btn-default" />
		</form>
		{% else %}
		<p>You must login to comment</p>
		<a href="{% url 'accounts:login' %}" class="btn btn-warning" role="button">Login</a>
		{% endif %}
	</div>


</div>


</div>

{% endblock content %}

templates/messages_display.html
{% if messages %}
<div class="messages">
<ul class="messages">
	{% for message in messages %}
	<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
	{% endfor %}
</ul>
{% endif %}
</div>

templates/post_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block head_extra %} 
{{ form.media }}
{% endblock %}

{% block content %}
<div class="col-sm-6">
<h1>Preview</h1>
<div class='content-preview'>
	<h3 id='preview-title'></h3>
	<p id='preview-content'></p>

	
</div>

</div>

<div class="col-sm-6 ">
<h1>{{ title }} </h1>

<form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
{{ form|crispy }}
<input type="submit", value="Create Post" class="btn btn-primary" role="button">
</form>
</div>
{% endblock content %}

templates/post_detail.html
{% extends "base.html" %}


{% load urlify %}
{% load crispy_forms_tags %}


{% block content %}

<section class="container post">
  <article>
    <h1>{{ instance.title }}
    	{% if instance.draft %}<small> <span style='color:red;'>草稿</span></small>{% endif %}
    </h1>
    <div class="meta">
      <span class="date">
        {{ instance.publish }}      </span>
      <span class="wordCount">
        {{ instance.words_count }}字
      </span>
      <span class="readingTime">
        {{ instance.read_time }}分钟      </span>
    </div>
    	{% autoescape off %} 
		{{ instance.content }}
		{% endautoescape %}
   </article>
  <span class="divider"></span>
  <div class="postend">
    
    <p>如果你喜欢这篇文章，分享给好友吧，分享到<a href="http://weibo.com">微博</a><br />
    <a href="/">点这里</a>，查看我的全部文章</p>
  </div>
</section>


<nav>
  <ul style="padding-left: 0px">
    <li class="older">
    {% if previous %}
                <a href="{{ previous.get_absolute_url }}" style="text-decoration: none;">
          <div class="content">
            <div class="postTitles">
              <div class="label">上一篇</div>
              <h3>{{ previous.title }}</h3>
            </div>
          </div>
        </a>
        {% endif %}
            </li>
        }
    <li class="newer">
    {% if next %}
                <a href="{{ next.get_absolute_url }}" style="text-decoration: none;">
          <div class="content">
            <div class="postTitles">
              <div class="label">下一篇</div>
              <h3>{{ next.title }}</h3>
            </div>
          </div>
        </a>
        {% endif %}
            </li>
  </ul>
</nav>


	
{% endblock content %}

templates/post_list.html
{% extends "base.html" %}


{% block content %}


<p><br /></p>

<section class="container blog center">


  <div class="intro">
    <h1>我是Ray，这里是我的小站</h1>
      <p>
        偶尔捣鼓代码，做做PS，写写文章，就有了这个小站<br /> 闲时会游泳、骑行或摄影，爱运动、爱设计、爱折腾<br />
        也可以联系我的<a href="http://weibo.com/5605009888/">微博</a>或者<a href="https://www.zhihu.com/people/rayiyaoyao">知乎</a>，讨论互联网二三事或者女性权利
      </p>
  </div>
    <span class="divider"></span>
</section>


<section class="posts center">
  {% for obj in object_list %}
  <div>
    <a class="post" href="{{ obj.get_absolute_url }}" style="text-decoration: none">
      <div class="content">
        <h1>{{ obj.title }}<small>{% if obj.draft %} <span style='color:red;'>Draft </span>{% endif %}</small></h1>
        <div class="meta">
          <span class="date">
            {{ obj.publish }}            </span>
          <span class="wordCount">
            {{ obj.words_count }}字          </span>
          <span class="readingTime">
            {{ obj.read_time }}分钟           </span>
        </div>
     </div>
      <div class="color left"></div>
      <div class="color right"></div>
    </a>
    </div>
    <p><br /></p>

  {% endfor %}   
</section>
  
        

 <section class="container thanks center">
    <span class="divider"></span>
    <p>Thanks for stopping by, I really appreciate it.<br />
    Copyright 2016 © Rayiyaoyao All rights reserved</p>  
</section>        
        








<!-- 
<div class="col-sm-8">
<nav aria-label="...">
  <ul class="pager">
    <!-- <span class="step-links" /> -->
    <!-- {% if object_list.has_previous %}
    <li><a href="?page={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">上一页</a></li>
    {% endif %}
    <span class="current">
    第{{ object_list.number }}页，共{{ object_list.paginator.num_pages }}页
    </span>
    {% if object_list.has_next %}
    <li><a href="?page={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">下一页</a></li>
    {% endif %}
  </ul>



</nav>  -->






{% endblock content %}